---
###  DO NOT CHANGE THE FOLLOWING PARAMETERS !!

# tmp war name when downloading
war_name: "{{app_name}}-{{app_version}}.war"

# final war name pushed to tomcat
war_name_dest: "{{app_context}}.war"

# download location
war_dists_dir: "{{app_base_dir}}/cluster_{{project_cluster_name}}/dists"