# -*- mode: ruby -*-
# vi: set ft=ruby :

# Lecture de la configuration
require 'yaml'

def symbolize_keys(hash)
  hash.inject({}){|result, (key, value)|
    new_key = case key
              when String then key.to_sym
              else key
              end
    new_value = case value
                when Hash then symbolize_keys(value)
                else value
                end
    result[new_key] = new_value
    result
  }
end

settings = YAML::load_file "settings.yml"
settings = symbolize_keys(settings)

# Configuration de la vm1
Vagrant.configure("2") do |config|
config.vm.define "ldc" do |ldc|
  # ce lien sera remplacer par un lien vers nexus
  ldc.vm.box = "https://atlas.hashicorp.com/centos/boxes/7/versions/1704.01/providers/virtualbox.box"
  ldc.vm.provider :virtualbox do |v|
    v.name = "ldc"
    v.customize [
      "modifyvm", :id,
      "--name", "ldc",
      "--memory", settings[:ram],
      "--natdnshostresolver1", "on",
      "--cpus", settings[:proc],
    ]
  end
  ldc.ssh.forward_agent = true

  ldc.vm.synced_folder "./", "/vagrant"
  ldc.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
  ldc.vm.network "forwarded_port", guest: 8091, host: 9191, auto_correct: true
  ldc.vm.network "forwarded_port", guest: 1080, host: 9080, auto_correct: true
  ldc.vm.network "private_network", ip: "10.2.2.2"	

  if Vagrant.has_plugin?("vagrant-proxyconf")
    ldc.proxy.http     = settings[:proxy]
    ldc.proxy.https    = settings[:proxy]
    ldc.proxy.no_proxy = "localhost,127.0.0.1"
  end
end
end