
- name: Check if Tomcat engine installation already exists
  stat: path={{tomcat_location}}/bin/version.sh
  register: t4_version_script

- name: if Tomcat is installed, check availability and version for user
  shell: $({{tomcat_location}})/bin/version.sh | grep "Server version:" | cut -d"/" -f2
  when: t4_version_script.stat.exists
  register: t4_version_installed
  changed_when: False
  environment: 
    JAVA_HOME: "{{jdk_home}}"
  become_user: "{{app_system_user}}"

- name: set var t4_already_installed
  set_fact: t4_already_installed="{{t4_version_installed is defined and t4_version_installed.stdout is defined and t4_version_installed.stdout == tomcat_version}}"
  tags: ['socle-technique']

- debug: msg="Installing tomcat engine {{tomcat_version}}"
  when: t4_already_installed != True
  tags: ['socle-technique']

- name: Check if tomcat package {{tomcat_version}} exist localy
  stat: path={{tomcat_download_location_filename}}
  register: tomcatpkg
  when: t4_already_installed != True
  tags: ['socle-technique']

- name: Download Tomcat package {{tomcat_version}}
  get_url: url={{tomcat_download_url}} dest={{tomcat_download_location_filename}} url_username={{artifactory_user}} url_password={{artifactory_pwd}}
  become: True
  when: t4_already_installed != True and tomcatpkg is defined and tomcatpkg.stat.exists != True
  tags: ['socle-technique']

- name: "Create tomcat main install dir (tomcat_all_installs_dir)"
  file: path={{ tomcat_all_installs_dir }} state=directory owner=root group=root mode=0755
  become: True
  when: t4_already_installed != True
  tags: ['socle-technique']

- name: "Create tomcat engine directory"
  file: path={{ tomcat_location }} state=directory owner=root group=root mode=0755
  become: True
  when: t4_already_installed != True
  tags: ['socle-technique']

- name: "Extract archive of Tomcat"
  unarchive: src="{{tomcat_download_location_filename}}" copy=no dest="{{tomcat_location}}" creates={{ tomcat_location }}/bin
  become: True
  when: t4_already_installed != True
  tags: ['socle-technique']



